### ISSUE TITLE
Code error when using Place  dataset

### ISSUE THREAD

**Issue by jchhuang** [zhmiao/OpenLongTailRecognition-OLTR#12]
When I use the Place dataset and implement the command “python3 main.py --config ./config/Places_LT/stage_1.py”，an error is occur, does anyone can help me? Thanks

Traceback (most recent call last):
  File "main.py", line 55, in <module>
    training_model = model(config, data, test=False)
  File "/home/huang/OpenLongTailRecognition-OLTR-master2/run_networks.py", line 26, in __init__
    self.init_models()
  File "/home/huang/OpenLongTailRecognition-OLTR-master2/run_networks.py", line 69, in init_models
    self.networks[key] = source_import(def_file).create_model(*model_args)
  File "./models/DotProductClassifier.py", line 17, in create_model
    clf = DotProduct_Classifier(num_classes, feat_dim)
  File "./models/DotProductClassifier.py", line 9, in __init__
    self.fc = nn.Linear(feat_dim, num_classes)
  File "/home/huang/.virtualenvs/OLTR/lib/python3.5/site-packages/torch/nn/modules/linear.py", line 76, in __init__
    self.weight = Parameter(torch.Tensor(out_features, in_features))
TypeError: new() received an invalid combination of arguments - got (str, bool), but expected one of:
 * (torch.device device)
 * (torch.Storage storage)
 * (Tensor other)
 * (tuple of ints size, torch.device device)
      didn't match because some of the arguments have invalid types: (str, bool)
 * (object data, torch.device device)
      didn't match because some of the arguments have invalid types: (str, bool)

**Comment by zhmiao** [comment]
Hello @jchhuang It seems the inputs of the `nn.linear` have some problems. Could you check if the inputs are correct?

**Comment by jchhuang** [comment]
Dear @zhmiao , I found when the model is initialized the input parameters are randomly ordered in the line of “ self.networks[key] = source_import(def_file).create_model(*model_args)” of run_network.py, and this phenomenon finally cause the above error, may you help to check why will cause the mis-ordered phenomenon.

**Comment by zhmiao** [comment]
Hello @jchhuang  , thanks for replying. I see the problem. We encountered this problem before as well. It was because we were using different python versions. I am not sure which python version you are using. To make sure it won't happen again, I think maybe saving the parameters to list, or using ordered dict can help.
