### ISSUE TITLE
Calculation of equation(6)

### ISSUE THREAD

**Issue by jchhuang** [zhmiao/OpenLongTailRecognition-OLTR#14]
I find some differences between ex of the equation (6) in paper and  the implementation in the code, may you help to check?

    def forward(self, input, *args):
        norm_x = torch.norm(input, 2, 1, keepdim=True)
        ex = (norm_x / (1 + norm_x)) * (input / norm_x)
        ew = self.weight / torch.norm(self.weight, 2, 1, keepdim=True)
    return torch.mm(self.scale * ex, ew.t())

**Comment by zhmiao** [comment]
Hello @jchhuang , thanks for asking. I guess it was a typo in the paper. However. we have tried both ways, here was little difference. You can try both ways of normalization as well.

**Comment by jchhuang** [comment]
Dear zhmiao, thanks a lot for your reply. In equation (3)， there is a ||* ||2, is it also a typo?

**Comment by zhmiao** [comment]
Hello @jchhuang , in equation (3) the reachability equation, since the 2 is an underscript, the ||* ||2 doesn't mean square, just another way of l2 norm, which is the same as we wrote in the code. I am sorry we did not keep the term consistent.
