### ISSUE TITLE
What's the difference and relationship between spatial attention and self attention

### ISSUE THREAD

**Issue by jchhuang** [zhmiao/OpenLongTailRecognition-OLTR#18]
Since both of the spatial and self attention are used in the modulated attention, in
 my understanding both of these two parts are used to capture the spatial information, so may you tell me what's the difference and relationship between spatial attention and self attention.

**Comment by zhmiao** [comment]
same as this issue: https://github.com/zhmiao/OpenLongTailRecognition-OLTR/issues/15#issuecomment-514042191
