### ISSUE TITLE
Overall vs F-measre

### ISSUE THREAD

**Issue by jchhuang** [zhmiao/OpenLongTailRecognition-OLTR#20]
For the datasets of ImageNet-LT and Places_LT, why only overall criterion is measured for close-set and only F-measure is measured for open-set other than these two indexes are used at the same time?   Under such incomplete comparison, it is easy cause doubts that the proposed algorithm do not work well.

**Comment by zhmiao** [comment]
@jchhuang This is because accuracy is a sufficient metric for close settings. F-measure we used is specifically designed for open settings. Please refer to the open max paper. Thanks.
