### ISSUE TITLE
Openset accuracy calculation is wrong

### ISSUE THREAD

**Issue by jchhuang** [zhmiao/OpenLongTailRecognition-OLTR#24]
@zhmiao As for the accuracy calculation, the correct equation is accuracy=TP/(TP+FP), however, in this repository the implementation of accuracy is replaced by recall (TP/(TP+FN))
![image](https://user-images.githubusercontent.com/16332360/62268707-42fab780-b463-11e9-9247-ac77d5baa7e9.png)
![image](https://user-images.githubusercontent.com/16332360/62268661-2199cb80-b463-11e9-99fd-f4f37a5d1066.png)

**Comment by zhmiao** [comment]
@jchhuang TP/(TP+FP) is not accuracy either, it is precision. Accuracy is (TP + TN) / total N.  We did not report this value in the paper. F-measurement is a better metric.
