### ISSUE TITLE
ClassAwareSampler configuration

### ISSUE THREAD

**Issue by jchhuang** [zhmiao/OpenLongTailRecognition-OLTR#34]
Hi, both in the Places and ImageNet,  the batch_size and number_samples_cls are configured as 256 and 4, respectively. Does it mean each batch only will contain 256/4=64 categories?

**Comment by zhmiao** [comment]
Hello @jchhuang , yes, you are right. for each mini-bach, it will only contain batch_num / samp_size randomly selected categories.
