### ISSUE TITLE
What's the purpose of “train plain” phase

### ISSUE THREAD

**Issue by jchhuang** [zhmiao/OpenLongTailRecognition-OLTR#40]
Except the “train”，“val”， there are also “train plain” phase, however what's the purpose of “train plain”？ or what's actions are taken during "train plain"

**Comment by Lilyo** [comment]
In my opinion, the purpose of “train plain” is used to calculate centroids without sampler

**Comment by zhmiao** [comment]
@jchhuang as @Lilyo said, it used for centroids calculation.
