### ISSUE TITLE
Missing very important baseline

### ISSUE THREAD

**Issue by twangnh** [zhmiao/OpenLongTailRecognition-OLTR#44]
Hi! Thanks for sharing your work, I'm wondering have you tried the baseline of class balanced sampling and inverse frequecy sampling when train the model?

**Comment by zhmiao** [comment]
@twangnh Thanks for asking. Yes, we have tried upsampling methods although we did not report it due to space limit. We also incorporated upsampling (class-aware samping) into our code. You are very welcome to single out this module and test it out.

**Comment by tonysy** [comment]
I think another important baseline is just use the weight normalization or cosine normalization without memory mechanism.

**Comment by liuziwei7** [comment]
All the comparison methods in Table 3 of the main paper (https://arxiv.org/pdf/1904.05160.pdf) are equipped with class-aware/balanced sampling, as elaborated in Section 4 "Competing Methods". You are more than welcome to try other variants of ablation study.
