### ISSUE TITLE
hyper-parameters

### ISSUE THREAD

**Issue by JasAva** [zhmiao/OpenLongTailRecognition-OLTR#45]
Hi, I'm curious if you could give some insights on how to decide the value of hyper-parameter scale (currently is set to 16) in the CosNormClassifier, is it set empirically or is there a theoretical way to set it? Also the parameter scale (currently is set to 10) in meta-embedding for reach-ability.

**Comment by zhmiao** [comment]
Hello @JasAva , these hyperparameters were tuned based on original implementations or other people's experiences. We would use their numbers first and then gradually tune these parameters to get better performance. Does that make sense?
