### ISSUE TITLE
Code on MS1M-LT dataset

### ISSUE THREAD

**Issue by LcDog** [zhmiao/OpenLongTailRecognition-OLTR#46]
Hi zhmiao,

Thanks for your code. 
I am wondering if you are planning to update the code (configs) for reproducing the results on the MS1M-LT dataset. Thanks.

**Comment by zhmiao** [comment]
Hello @LcDog , thank you very much for asking. I think in the short term, we are not planning on publishing the MS1M-LT code. I will check with my collaborator about sharing the dataset first. Once it is published, we will notify you as soon as possible.

**Comment by liuziwei7** [comment]
The MS1M-LT dataset is already available at our OLTR benchmark link: https://drive.google.com/open?id=1j7Nkfe6ZhzKFXePHdsseeeGI877Xu1yf .

**Comment by LcDog** [comment]
@zhmiao @liuziwei7 Thanks!
