### ISSUE TITLE
CosNormClassifier#L24 

### ISSUE THREAD

**Issue by sudabai666** [zhmiao/OpenLongTailRecognition-OLTR#5]
Hi,
Thank you for releasing the code for your paper. I'm a little confused when I look at this line of code.
[https://github.com/zhmiao/OpenLongTailRecognition-OLTR/models/CosNormClassifier.py#L24](url). 
It seems to be different from what is described in the paper. Could you help me with this problem?

Thank you very much.

**Comment by zhmiao** [comment]
Hello @sudabai666 Thank you for asking. Could you please be a little more specific on which part you are having a problem with? Thanks again.

**Comment by zhmiao** [comment]
Since it has been more than 20 days, we will close this issue by now. If you are having more questions, we will open it again. Thank you very much!

**Comment by drcege** [comment]
I guess he means  Eq.(6).

Should be 
`ex = (norm_x**2  / (1 + norm_x**2)) * (input / norm_x)` 
instead of  
`ex = (norm_x / (1 + norm_x)) * (input / norm_x)`.

**Comment by zhmiao** [comment]
@drcege and @sudabai666  Thanks for asking. As in issue #14 actually it was a typo in the paper. However, we have tried both ways for the normalization, with and without squares, it worked almost the same. You are welcomed to test it out as well. We will fix it in the text as soon as possible!

**Comment by milliema** [comment]
@zhmiao I find it's confused to use reachability and CosNormClassifier. Since the feature will be normalized in CosNormClassifier, why bother scaling it with reachability?
