### ISSUE TITLE
embedded_gaussian is not trained

### ISSUE THREAD

**Issue by ily-R** [zhmiao/OpenLongTailRecognition-OLTR#53]
https://github.com/zhmiao/OpenLongTailRecognition-OLTR/blob/4dc25ea546bbcb0f84033f8187509a9d0b96fab3/run_networks.py#L76

Seeing this line, Stage1 config and Stage2 config, I noticed that embedded gaussian non-local filtering is not trained at all as "selfatt" is not present in ModulatedAttLayer. In Stage 1 we don't use the modulated attention  https://github.com/zhmiao/OpenLongTailRecognition-OLTR/blob/4dc25ea546bbcb0f84033f8187509a9d0b96fab3/config/Places_LT/stage_1.py#L19

In Stage 2 we use it: https://github.com/zhmiao/OpenLongTailRecognition-OLTR/blob/4dc25ea546bbcb0f84033f8187509a9d0b96fab3/config/Places_LT/stage_2_meta_embedding.py#L20
initialize it, but then fix all the convolution layers weights due to:
https://github.com/zhmiao/OpenLongTailRecognition-OLTR/blob/4dc25ea546bbcb0f84033f8187509a9d0b96fab3/config/Places_LT/stage_2_meta_embedding.py#L26

and the above if condition.

Should we change "selfatt" to "modulatedatt"

**Comment by zhmiao** [comment]
Hello @ily-R , thanks for asking. I think you are right, we need to change this to modulatedatt. I think it is a bug when we were renaming modules for code publication. We will update the code asao

**Comment by zhmiao** [comment]
Hello @ily-R , the codes are updated, and we have newly implemented results and weights for Places-LT as well. Please check it out. Thanks.

**Comment by ily-R** [comment]
Thank you ! I will check it out.
