### ISSUE TITLE
Implementation for methods cost sensitive, meta regression and meta model net?

### ISSUE THREAD

**Issue by qingge545** [zhmiao/OpenLongTailRecognition-OLTR#54]
You list different methods results in the paper, and I wonder if you have the implementation for the other methods? Thank you !

**Comment by zhmiao** [comment]
Hello @qingge545 , thank you very much for asking and sorry for the late reply. Currently we do not have code ready for publication on the baseline methods. But most of them are directly from implementation published on github. Thanks again.
