### ISSUE TITLE
 Reproducing OLTR results

### ISSUE THREAD

**Issue by DinSangrasi** [zhmiao/OpenLongTailRecognition-OLTR#55]
I am facing a bit of trouble while reproducing the result.
Could you please guide the easy steps with illustrations (if possible) to reproduce the results. One of the error messages is given below:

FileNotFoundError: [Errno 2] No such file or directory: '/home/dms947/MY_EXPERIMENTS/OLTR_CVPR 2019/OpenLongTailRecognition/Root_DataSets/ImageNet_2014/train/n03903868/n03903868_47159.JPEG'

When I verified, the image n03903868_47159.JPEG in the ImageNet_2014 dataset does not exist.

**Comment by zhmiao** [comment]
Hello @DinSangrasi , thank you very much for asking and sorry for the late reply! I am not sure why you have this problem. It seems we have this image on our end?

**Comment by DinSangrasi** [comment]
Thanks Zhmiao for your reply. It's ok I have resolved the issue.
________________________________

**Comment by TalentedMUSE** [comment]
> 

How do you solve this problem? I met the same problem that some of the folders in the ImageNet2014 train dataset are missing.
![image](https://user-images.githubusercontent.com/39563262/170079269-0d214105-4ba1-4146-9744-e961c7337368.png)
As you can see, there is no "n03903868"
Thank you~~~

**Comment by biter0088** [comment]
I have the same problem.
`FileNotFoundError: [Errno 2] No such file or directory: '/home/xiu/Learning/datasets/ImageNet_2014/train/n03899768/n03899768_14428.JPEG'`

![图片](https://github.com/user-attachments/assets/91ace902-d73d-4003-88be-dea79d6ffbbf)

**Comment by biter0088** [comment]
Need  to download `CLS-LOC dataset`, and I have write a note at: https://blog.csdn.net/BIT_HXZ/article/details/141039153
![1](https://github.com/user-attachments/assets/4b9c198e-1551-4772-ac79-2940b37e31c2)
![2](https://github.com/user-attachments/assets/c2142e92-780f-4ec7-90d6-b272c730d1af)
![3](https://github.com/user-attachments/assets/87ae5c35-ca3f-4918-99fa-5e9a057c366d)
![4](https://github.com/user-attachments/assets/ac56d607-e4ab-4224-9afd-ebe0c81c94a6)
![5](https://github.com/user-attachments/assets/8f8735a4-1794-4016-a2e9-5c4fc723eb13)
