### ISSUE TITLE
Table 2 results

### ISSUE THREAD

**Issue by zaeemzadeh** [zhmiao/OpenLongTailRecognition-OLTR#58]
Hi,
Thanks for sharing your work. Is there an easy way (without changing the code much) to reproduce Table 2 results? (CIFAR100 + TinyImagenet (resized))

**Comment by zhmiao** [comment]
Hello @zaeemzadeh , thank you very much for asking and sorry for the late reply. Yes, if you want to apply out code to other datasets, the easiest way is to change the dataset object defined in the code. However, CIFAR has different dimensions than ImageNet. So I think you will also want to change the model definition. On the other hand, direct using the hyperparameters we have for ImageNet won't provide good results either. Does that make sense?

**Comment by zaeemzadeh** [comment]
Thanks. Yes it makes sense
