### ISSUE TITLE
the use of fc layer

### ISSUE THREAD

**Issue by cl475143764** [zhmiao/OpenLongTailRecognition-OLTR#60]
thanks for such a great work, but there is a issue for me,  when i used the resnet152 as a backbone, it was too large for the centroids,like(1e+8), so the distance between the center and sample feature is too large, finally the net did not converge. could you please give me a help? thanks a lot!

**Comment by zhmiao** [comment]
Hello @cl475143764 , I am really sorry for the late reply! What do you mean by "too large" ? Is it the dimension or the number of centroids? As the feature dimension for resnet152 is 2048, (128 if using an additional fc layer), it should not be too large. If we are talking about the number of centroids, it should be equal to the number of classes. I don't know how did you get the 1e+8?

**Comment by zhmiao** [comment]
As it has been over three months, I will close this issue for now. If you have any more questions, you are welcome to reopen it. Thanks.
