### ISSUE TITLE
the accuracy of the train and val

### ISSUE THREAD

**Issue by cl475143764** [zhmiao/OpenLongTailRecognition-OLTR#61]
thanks for such a beautiful work. but i have a question about the acc between the train and val. in the train phase, the network could converge finally and got a high acc on the train_set, but in the test phase, when i used the test-set, the network's acc became very low, so i tried to use the train data to verify the weights is right, but the result was that it was also so worse, i tried to check what's wrong, but i had no idea about it, could you please give me a advice? thanks a lot!

**Comment by zhmiao** [comment]
Hello @cl475143764, thank you very much for asking and sorry for the late reply! I think this might because the model is not properly saved. Did you change anything in the original code?

**Comment by zhmiao** [comment]
As it has been over three months, I will close this issue for now. If you have any more questions, you are welcome to reopen it. Thanks.
