### ISSUE TITLE
Caffe pretrained models

### ISSUE THREAD

**Issue by drcege** [zhmiao/OpenLongTailRecognition-OLTR#9]
Hi, where did you get the Caffe pretrained ResNet152  as well as the ResNet-10 and  ResNet-50 mentioned in the paper?

Are they from [Kaiming He's repository](https://github.com/KaimingHe/deep-residual-networks), and how did you convert them to pytorch format?

**Comment by drcege** [comment]
By the way, which Places dataset should I download? There are three 256*256 versions on their website:
- Places365-Standard (256 * 256)
- Places365-Standard (256 * 256) with easy directory structure
- Places365-Challenge 2016 (256 * 256)

**Comment by zhmiao** [comment]
Hello @drcege , thanks for asking. the caffe pretrained model was downloaded from this repo: https://github.com/ruotianluo/pytorch-resnet . We found that if freezing the convolutional weights, directly using the pytorch official weights would give us suboptimal results. 

For the Places we used the Places365-Standard (256 x 256) version. 

Thank you very much.
